config/routes.rb
Rails.application.routes.draw do

  get 'facturas/index'

  resources :facturas
  resources :facturas
  resources :facturas
  resources :facturas
  resources :invoices
  resources :boleta
  mount Spree::Core::Engine, at: '/tienda/'

  root 'welcome#index2'

  get 'twi/:mensaje' => 'welcome#twitt'

  get 'face/:mensaje' => 'welcome#face'

  get 'vars' => 'api#vars'

  get 'doc' => 'welcome#doc', path: 'api/documentacion'
  get 'orders' => 'ordens#index', path: 'orders'
  get 'facturas' => 'facturas#index', path: 'facturas'
  get 'transactions' => 'transactions#index', path: 'transactions'
  get 'panel' => 'dashboard#panel', path: 'panel'
  get 'dashboard' => 'dashboard#index', path: 'dashboard'
  get 'index2' => 'welcome#index2', path: 'welcome/index2'
  post 'chagen_date' => 'dashboard#reload',path:'reloadCharts'

  get 'static_table' => 'welcome#static_table', path: 'static_table.html.erb'
  get 'datatable' => 'welcome#datatable', path: 'datatable.html.erb'

  get 'success' =>'welcome#success', path: 'tienda/success/:id'

  get 'error' =>'welcome#error', path: 'tienda/error'
  get 'error' =>'welcome#stock', path: 'tienda/stock'
  get 'error' =>'welcome#noAddress', path: 'tienda/noAddress'

  get 'api/facturas/recibir/:idfact' => 'api#fact_recibir'

  get 'api/producirArroz' => 'api#producirArrozOnline'

  get 'api/producirAzucar' => 'api#producirAzucarOnline'

  get 'api/verBodegas' => 'api#verBodegas'

  get 'api' => 'api#cambiar'
  get 'api/hash' => 'api#hash'

  get 'api/test' => 'api#test'

  get 'api/procesarFtp' => 'api#procesarFtp'

  get 'api/vaciarRecepcion' => 'api#vaciarBodegaRecepcionOnline'

  get 'api/vaciarPulmon' => 'api#vaciarPulmonOnline'

  get 'api/consultar/:sku' => 'api#consultar'

  get 'api/test' => 'api#test'

  get 'api/leerFtp' => 'api#leerFtp'

  get 'api/oc/recibir/:idoc' => 'api#recibir'

  get 'api/pagos/recibir' => 'api#pago_recibir'

  get 'api/despachos/recibir/:idfactura' =>'api#recibir_despacho'

end

app/models/factura.rb
class Factura < ActiveRecord::Base
end

app/controllers/facturas_controller.rb
class FacturasController < ApplicationController
  before_action :set_factura, only: [:show, :edit, :update, :destroy]

  # GET /facturas
  # GET /facturas.json
  def index
    @facturas = Factura.all
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/views/facturas/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facturas/_index.html.erb
<div class="padding-md" id="facturasPanel">
  <ul class="breadcrumb">
    <li><span class="primary-font"><i class="icon-home"></i></span><a> Inicio</a></li>
    <li>Facturas</li>
  </ul>
  <table class="table table-striped" id="dataTable">
    <thead>
    <tr>
      <th>Id Factura</th>
      <th>Cliente</th>
      <th>Proveedor</th>
      <th>Valor Bruto</th>
      <th>Iva</th>
      <th>Estado</th>
      <th>Id OC</th>
      <th>Id Transacción</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @facturas.each do |invoice| %>
        <tr>
          <td><%= invoice.idfact %></td>
          <td><%= invoice.cliente %></td>
          <td><%= invoice.proveedor %></td>
          <td><%= invoice.valor_bruto %></td>
          <td><%= invoice.iva %></td>
          <td><%= invoice.estado %></td>
          <td><%= invoice.idoc %></td>
          <td><%= invoice.idtrx %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div><!-- ./padding-md -->

app/views/facturas/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/facturas/index.js.erb
$('.main-container').find('#orders').remove();
$('.main-container').find('#transactions').remove();
$('.main-container').find('#facturasPanel').remove();
$('#panel').hide();
$('.main-container').hide().append("<%= j render :partial =>  'facturas/index' %>").fadeIn('slow')

app/views/facturas/new.html.erb
<h1>New Invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/facturas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>