config/routes.rb
Rails.application.routes.draw do

  get 'facturas/index'

  resources :facturas
  resources :facturas
  resources :facturas
  resources :facturas
  resources :invoices
  resources :boleta
  mount Spree::Core::Engine, at: '/tienda/'

  root 'welcome#index2'

  get 'twi/:mensaje' => 'welcome#twitt'

  get 'face/:mensaje' => 'welcome#face'

  get 'vars' => 'api#vars'

  get 'doc' => 'welcome#doc', path: 'api/documentacion'
  get 'orders' => 'ordens#index', path: 'orders'
  get 'facturas' => 'facturas#index', path: 'facturas'
  get 'transactions' => 'transactions#index', path: 'transactions'
  get 'panel' => 'dashboard#panel', path: 'panel'
  get 'dashboard' => 'dashboard#index', path: 'dashboard'
  get 'index2' => 'welcome#index2', path: 'welcome/index2'
  post 'chagen_date' => 'dashboard#reload',path:'reloadCharts'

  get 'static_table' => 'welcome#static_table', path: 'static_table.html.erb'
  get 'datatable' => 'welcome#datatable', path: 'datatable.html.erb'

  get 'success' =>'welcome#success', path: 'tienda/success/:id'

  get 'error' =>'welcome#error', path: 'tienda/error'
  get 'error' =>'welcome#stock', path: 'tienda/stock'
  get 'error' =>'welcome#noAddress', path: 'tienda/noAddress'

  get 'api/facturas/recibir/:idfact' => 'api#fact_recibir'

  get 'api/producirArroz' => 'api#producirArrozOnline'

  get 'api/producirAzucar' => 'api#producirAzucarOnline'

  get 'api/verBodegas' => 'api#verBodegas'

  get 'api' => 'api#cambiar'
  get 'api/hash' => 'api#hash'

  get 'api/test' => 'api#test'

  get 'api/procesarFtp' => 'api#procesarFtp'

  get 'api/vaciarRecepcion' => 'api#vaciarBodegaRecepcionOnline'

  get 'api/vaciarPulmon' => 'api#vaciarPulmonOnline'

  get 'api/consultar/:sku' => 'api#consultar'

  get 'api/test' => 'api#test'

  get 'api/leerFtp' => 'api#leerFtp'

  get 'api/oc/recibir/:idoc' => 'api#recibir'

  get 'api/pagos/recibir' => 'api#pago_recibir'

  get 'api/despachos/recibir/:idfactura' =>'api#recibir_despacho'

end

app/controllers/welcome_controller.rb
require "http"
require "base64"
require "cgi"
require "openssl"
require "json"
require 'koala'
require 'proms_module'


class WelcomeController < ApplicationController
	include PromsModule

	def index

	end

	def index2

	end


	def doc

	end

	def success
		id = params[:id]
		@invoice = Boletum.where(id_boleta: id)[0]
	end




	def twitt

		tweet = twitte params[:mensaje]  , "nada"

	   response = { :estado => "aceptado", :tweet => tweet}
		render :json => response

	end




	def face

		msg = publica params[:mensaje] , "nada"

	   response = { :estado => "aceptado", :tweet => msg}
		render :json => response

	end


	def promocionar (mensaje, url)
		faceboki mensaje url
		twitt mensaje
	end




end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/datatable.html.erb
<% content_for :content do %>
			<div class="main-container">
				<div class="padding-md">
					<ul class="breadcrumb">
						<li><span class="primary-font"><i class="icon-home"></i></span><a href="../index.html"> Home</a></li>
						<li>Table</li>
						<li>Datatable</li>
					</ul>

					<table class="table table-striped" id="dataTable">
						<thead>
							<tr>
								<th>No</th>
								<th>Product</th>
								<th>Price</th>
								<th>Quantity</th>
								<th>Sales</th>
								<th>Date</th>
								<th>Status</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>#1001</td>
								<td>Leather Bag</td>
								<td>$89</td>
								<td>30</td>
								<td>187</td>
								<td>Oct 08,2013</td>
								<td><span class="label label-success">In Stock</span></td>
							</tr>
							<tr>
								<td>#1002</td>
								<td>Brown Sunglasses <span class="label label-success m-left-xs">Best Seller</span> </td>
								<td>$120</td>
								<td>0</td>
								<td>861</td>
								<td>Oct 07,2013</td>
								<td><span class="label label-danger">Sold Out</span></td>
							</tr>
							<tr>
								<td>#1003</td>
								<td>Casual Boots</td>
								<td>$99</td>
								<td>100</td>
								<td>12</td>
								<td>Oct 06,2013</td>
								<td><span class="label label-success">In Stock</span></td>
							</tr>
							<tr>
								<td>#1004</td>
								<td>Lambskin Sport Coat</td>
								<td>$4000</td>
								<td>7</td>
								<td>41</td>
								<td>Oct 06,2013</td>
								<td><span class="label label-success">In Stock</span></td>
							</tr>
							<tr>
								<td>#1005</td>
								<td>Summer Dress</td>
								<td>$310</td>
								<td>25</td>
								<td>39</td>
								<td>Oct 05,2013</td>
								<td><span class="label label-success">In Stock</span></td>
							</tr>
							<tr>
								<td>#1006</td>
								<td>Duffle Coat</td>
								<td>$80</td>
								<td>0</td>
								<td>20</td>
								<td>Sep 30,2013</td>
								<td><span class="label label-danger">Sold out</span></td>
							</tr>
							<tr>
								<td>#1007</td>
								<td>Universal Camera Case</td>
								<td>$35</td>
								<td>30</td>
								<td>3</td>
								<td>Sep 29,2013</td>
								<td><span class="label label-success">In Stock</span></td>
							</tr>
							<tr>
								<td>#1008</td>
								<td>Leopard Rose Dress</td>
								<td>$1500</td>
								<td>10</td>
								<td>1</td>
								<td>Sep 27,2013</td>
								<td><span class="label label-success">In Stock</span></td>
							</tr>
							<tr>
								<td>#1009</td>
								<td>Casual stripe</td>
								<td>$50</td>
								<td>30</td>
								<td>25</td>
								<td>Sep 27,2013</td>
								<td><span class="label label-success">Sold out</span></td>
							</tr>
							<tr>
								<td>#1010</td>
								<td>Italian shirt</td>
								<td>$70</td>
								<td>40</td>
								<td>4</td>
								<td>Sep 27,2013</td>
								<td><span class="label label-info">Promotion</span></td>
							</tr>
							<tr>
								<td>#1011</td>
								<td>Iphone 5</td>
								<td>$400</td>
								<td>300</td>
								<td>152</td>
								<td>Sep 27,2013</td>
								<td><span class="label label-danger">In stock</span></td>
							</tr>
							<tr>
								<td>#1012</td>
								<td>Ipad</td>
								<td>$350</td>
								<td>46</td>
								<td>103</td>
								<td>Sep 25,2013</td>
								<td><span class="label label-success">In Stock</span></td>
							</tr>
						</tbody>
					</table>
				</div><!-- ./padding-md -->
			</div><!-- /main-container -->
<% end %>

app/views/welcome/doc.html.erb
<%= content_for :links do %>
    <%= javascript_include_tag 'static_table'%>
<% end %>
<% content_for :content do %>
    <div class="padding">
          <div class="page-title">
            Documentación
          </div>
          <div class="page-sub-header">
            Bienvenido a la documentación del grupo 6
          </div>
          <h2>Datos del Grupo</h2>
          <p>ID Grupo: 571262b8a980ba030058ab54</p>
          <p>ID Banco: 571262c3a980ba030058ab62</p>

          <h2>Métodos</h2>
          <h3>1. /api/consultar/:sku</h3>
          <p> GET. Como parámetro se necesita el sku del producto que se está consultando</p>
          <p>Como respuesta retorna el stock que hay del producto como un Json de la forma: {“stock”: int, “sku”: int}</p>


          <h3>2. /api/oc/recibir/:idoc</h3>
          <p> GET. Como parámetro se necesita id de la orden de compra</p>
          <p>Como respuesta retorna si se aceptó o no la orden de compra como Json de la forma: {“aceptado”: boolean, “idoc”: string}</p>

          <h3>3. 'api/pagos/recibir/idtrx=:idtrx&idfactura=:idfactura'</h3>
          <p> GET. Como parámetro se necesita id de la transacción y de la factura</p>
          <p>Como respuesta retorna la validación de la factura con un Json de la forma: {“validado”: boolean, “idtrx”: string}</p>

          <h3>4. /api/despachos/recibir/.:idfactura</h3>
          <p> GET. Como parámetro se necesita id de la factura para consultar que es valido</p>
          <p>Como respuesta retorna la validación del despacho con un Json de la forma: {“validado”: boolean}</p>
        </div>


<% end %>

app/views/welcome/error.html.erb
<!DOCTYPE html>
<div class='row'>
  <div class= 'col-md-2'></div>
  <div class= 'col-md-6'>
<h1> Hubo un error en su compra</h1>
<h3> Intente regresar a nuestra tienda</h3>

<br>
<br>
<%=  link_to 'Tienda 6commerce', '/tienda/' %>

</div>
</html>

app/views/welcome/index2.html.erb
<%= content_for :links do %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
<% end %>
<% content_for :content do %>



  <div class="main-container">
    <div class="padding-md">


		<div class='row'>
		  <div class= 'col-md-2'></div>
		  <div class= 'col-md-6'>
			<h1> Grupo 6 </h1>
			<h3> ¡Estamos de vuelta!</h3>
			<h4>- Más fuertes que nunca -</h4>
			<br>
			<br>
			<%=  link_to 'Documentación de nuestra API', doc_path %>
			<br>
			<br>
			<%=  link_to 'Tienda 6commerce', '/tienda/' %>

			<br>
			<br>
			<%=  link_to 'Dashboard y órdenes', '/dashboard' %>
      <br>
      <br>
      <%=  link_to 'Login como admin', '/tienda/admin' %>
      <br>
      <br>
		   </div>
		 </div>

	</div>
   </div>

<% end %>

app/views/welcome/noAddress.html.erb
<% content_for :content do %>
<div class='row' style="text-align:center">
  <br>
  <br>
<h1> Hubo un error en su compra</h1>
<h3> Debe ingresar una dirección de despacho</h3>

<br>
<br>
<%=  link_to '< Volver a tienda', '/tienda/' %>

</div>
<% end %>

app/views/welcome/stock.html.erb
<% content_for :content do %>
<div class='row' style="text-align:center">
  <br>
  <br>
<h1> Hubo un error en su compra</h1>
<h3> La cantidad requerida no se encuentra disponible en este momento</h3>

<br>
<br>
<%=  link_to '< Volver a tienda', '/tienda/' %>

</div>
<% end %>

app/views/welcome/success.html.erb
<% content_for :content do %>
<div class="main-container">
  <div class="padding-md">

    <h1>
      Compra realizada con éxito!</h1>
    <br>
    <div class='row'>
      <div class='col-md-2'></div>
      <div class='col-md-6' style="border:solid; text-align:center;">

        <h3 style="border-bottom:solid">
          DATOS DE LA COMPRA</h3>
          <h4>id:
            <%= @invoice.id %></h4>
        <h4>Dirección:
          <%= @invoice.cliente %></h4>
          <br>

        <h4>  Valor Bruto:
          <%= @invoice.bruto %></h4>
        <h4>  IVA:
          <%= @invoice.iva %></h4>
        <h2 style="border-top:solid; padding-top:10px">Total: $<%= @invoice.total %></h2>
        <br>

      </div>
    </div>
      <div class="row">

        <br>
        <%=  link_to '< Volver a tienda', '/tienda/' %>

</div>
    </div>

  </div>
</div>
<% end %>