config/routes.rb
Rails.application.routes.draw do

  get 'facturas/index'

  resources :facturas
  resources :facturas
  resources :facturas
  resources :facturas
  resources :invoices
  resources :boleta
  mount Spree::Core::Engine, at: '/tienda/'

  root 'welcome#index2'

  get 'twi/:mensaje' => 'welcome#twitt'

  get 'face/:mensaje' => 'welcome#face'

  get 'vars' => 'api#vars'

  get 'doc' => 'welcome#doc', path: 'api/documentacion'
  get 'orders' => 'ordens#index', path: 'orders'
  get 'facturas' => 'facturas#index', path: 'facturas'
  get 'transactions' => 'transactions#index', path: 'transactions'
  get 'panel' => 'dashboard#panel', path: 'panel'
  get 'dashboard' => 'dashboard#index', path: 'dashboard'
  get 'index2' => 'welcome#index2', path: 'welcome/index2'
  post 'chagen_date' => 'dashboard#reload',path:'reloadCharts'

  get 'static_table' => 'welcome#static_table', path: 'static_table.html.erb'
  get 'datatable' => 'welcome#datatable', path: 'datatable.html.erb'

  get 'success' =>'welcome#success', path: 'tienda/success/:id'

  get 'error' =>'welcome#error', path: 'tienda/error'
  get 'error' =>'welcome#stock', path: 'tienda/stock'
  get 'error' =>'welcome#noAddress', path: 'tienda/noAddress'

  get 'api/facturas/recibir/:idfact' => 'api#fact_recibir'

  get 'api/producirArroz' => 'api#producirArrozOnline'

  get 'api/producirAzucar' => 'api#producirAzucarOnline'

  get 'api/verBodegas' => 'api#verBodegas'

  get 'api' => 'api#cambiar'
  get 'api/hash' => 'api#hash'

  get 'api/test' => 'api#test'

  get 'api/procesarFtp' => 'api#procesarFtp'

  get 'api/vaciarRecepcion' => 'api#vaciarBodegaRecepcionOnline'

  get 'api/vaciarPulmon' => 'api#vaciarPulmonOnline'

  get 'api/consultar/:sku' => 'api#consultar'

  get 'api/test' => 'api#test'

  get 'api/leerFtp' => 'api#leerFtp'

  get 'api/oc/recibir/:idoc' => 'api#recibir'

  get 'api/pagos/recibir' => 'api#pago_recibir'

  get 'api/despachos/recibir/:idfactura' =>'api#recibir_despacho'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
    respond_to do |format|
      format.js
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.fetch(:transaction, {})
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/_index.html.erb
<div class="padding-md" id="transactions">
  <ul class="breadcrumb">
    <li><span class="primary-font"><i class="icon-home"></i></span><a>Inicio</a></li>
    <li>Transacciones</li>
  </ul>
  <table class="table table-striped" id="dataTable">
    <thead>
    <tr>
      <th>Id Transacción</th>
      <th>Monto</th>
      <th>Cuenta Origen</th>
      <th>Cuenta Destino</th>
      <th>Grupo Origen</th>
      <th>Grupo Destino</th>
      <th>Usada</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.idtrx %></td>
          <td><%= transaction.monto %></td>
          <td><%= transaction.cuenta_o %></td>
          <td><%= transaction.cuenta_d %></td>
          <td><%= transaction.grupo_o %></td>
          <td><%= transaction.grupo_d %></td>
          <td><%= transaction.usada %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div><!-- ./padding-md -->

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.js.erb
$('.main-container').find('#transactions').remove();
$('.main-container').find('#orders').remove();
$('.main-container').find('#facturasPanel').remove();

$('#panel').hide();
$('.main-container').hide().append("<%= j render :partial =>  'transactions/index' %>").fadeIn('slow');

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>